version: '3'
services:
    nodejs:
        build:
            context: brainbeatsfront
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        networks:
          - app-network
        ports:
          - "3000:5000"
        command:
            serve -s build
            
        depends_on:
          - db
        environment:
            MONGO_USERNAME: username
            MONGO_PASSWORD: password
            MONGO_HOSTNAME: db
            MONGO_PORT: 27017
            MONGO_DB: bbdb

    db:
        image: mongo:4.1.8-xenial
        container_name: db
        restart: unless-stopped
        environment:
          MONGO_INITDB_ROOT_USERNAME: username
          MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
          - dbdata:/data/db
        networks:
          - app-network
            
networks:
    app-network:
        driver: bridge
        
volumes:
  dbdata:
